#!/usr/bin/env bash
# NOTE: assumes python3 is installed

# make sure pip is installed
python3 -m ensurepip --upgrade

# create (if needed) & enter virtual environment to prevent 'externally managed' errors
if [ ! -d "./venv" ]; then
    python3 -m venv ./venv 
fi

source ./venv/bin/activate

# install libraries needed for bootstrap script
pip install questionary requests

# run bootstrap python script
./bootstrap.py

# exit venv
deactivate

echo "Done!"
