general {
    lock_cmd = pidof hyprlock || hyprlock       # Avoids starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # Securely locks before the system suspends
}

# turn off monitors after 15 mins
listener {
    timeout = 900
    on-timeout = niri msg action power-off-monitors
    on-resume = niri msg action power-on-monitors
}

# go to sleep after 30 mins
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
